name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      test_type:
        description: 'Type of test to run'
        required: true
        default: 'functional'
        type: choice
        options:
          - functional
          - performance

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      API_KEY: ${{ secrets.API_KEY }}
    strategy:
      matrix:
        test_type: [functional, performance]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Compose
      run: sudo apt-get update && sudo apt-get install -y docker-compose

    - name: Run functional tests
      if: matrix.test_type == 'functional' || github.event.inputs.test_type == 'functional'
      run: docker-compose up k6-functional

    - name: Run performance tests
      if: matrix.test_type == 'performance' || github.event.inputs.test_type == 'performance'
      run: docker-compose up k6-performance
